#!/bin/bash

# Post-receive hook for pushing changes to origin

norev="0000000000000000000000000000000000000000"

REFS=()
while read oldrev newrev refname
do
    if [[ "$newrev" == "$norev" ]]
    then
        # branch deleted
        REFS+=(":$refname")
    else
        # branch added or updated
        REFS+=("+$refname:$refname")
    fi
done

# see setup-synchronize-git-repositories-with-satellite.sh
/path/to/sync-script other-remote "${REFS[*]}"
